### ISSUE TITLE
Really non-blocking?

### ISSUE THREAD

**Issue by jmichalon** [mah0x211/lua-process#1]
Hi,

Using this lib to start a compilation of some software, it stalls after some time, like if the gcc processes were suddenly paused.
I think that it may be due to the stdout/stderr pipe being full.
The caller uses child:stdout/stderr but shows output only from time to time, tens of lines at once.
I tried to play with nohang to no avail.
Now I'm wondering if the calls are really non-blocking as it looks like it should. I see nowhere in lua-process' code a call with O_NONBLOCK. I think that calls to dup2 in iop_set could need to specify this. Currently, without this, if we poll continuously on stderr and stdout, if one of the two is blocking, the second one will never be read and the processes would block waiting to be able to write.

Best Regards.

**Comment by mah0x211** [comment]
Implementations of read and write support non-blocking mode, but descriptors are not in non-blocking mode. That is bug in the document that causes the reader's misunderstandings.

I added a non-blocking mode option to exec function of version 1.8.1. 
If you necessary that feature, consider using v1.8.1 or later.

thanks.
